<font size="8">Homework 2: Mini Project - AirBnb Document Database</font>

Group number: `<NA>`

Group members:
1. `<Alexandre Spagnol> : <20230434>`
2. `<Filipe Rodrigues> : <m20201866>`
3. `<Gonçalo Ferreira> : <20230492>`
4. `<Hugo Alves> : <20230438>`

The Homework 2 is comprised of two parts:
1. Data modelling
2. Queries to database to answer the questions

<font size="6">1. Data Modelling</font>

<font size="4">Congratulations! You have been successfully hired as the new Data Engineering and Management team in the AirBNB Business Intelligence department. 
The organization is undergoing restructuring as the performance of the previous teams was not believed to be satisfactory.

Before leaving their post, the head of the Data Modelling department left this note of identified issues.

Currently a lot of data related to AirBNB listings is all collected in the same document. While this has some advantages it has also caused issues. The query performance is known to be too slow, so some decisions on hybridization of data models are required. The previous team did not have experience in the application of patterns, which has been identified as a key area to improve performance through the enhancement of the data model. Indexes have also not been previously applied.

The AirBNB application use has been growing rapidly, especially the the number of reviews. Because of that we have been overwriting them regularly, but the business intelligence department will benefit from storing all the Reviews and analysing them over time. 

Finally, there are some mistakes in the data collection : for instance, writing the same data multiple times, and assigning wrong timestamps for when transactions occurred. The new team will need to decide how to address these.   

In your new role, you are expected to think about the database use case in each question, analyse all the information you have, how commonly is this query needed, how heavy will it be on reads and write etc. You should modify the database schema, where you deem appropriate, to optimise for the business use cases. To do so you should use all the tools you have learned in the lab and lectures, especially embedding and linking, indexes, and patterns. This can involve creating new fields, documents, and collections. Indicate which pattern you are applying and your reasoning for doing so in comments, remember to identify any duplication that is required and any risks of staleness. 

Remember to think about the relevancy of all data that will be returned in each case and if this is needed or adding excessive time to return:
1. to streamline the data collection system;
2. to clean up the data and optimise what will be returned for each use case;
3. to use correct patterns to improve speed of typical queries;
4. to ensure that all departments receive correct and relevant information from the database;
5. to provide the data model schema to inform other departments of the changes.

Good practices in our company include:
1. all newly created fields have CAPITALIZED names;
2. all new queries function on the most updated version of the database (if you make multiple changes all your queries still work after the final changes);
3. for some of the queries you will likely want to change the database schema in some way. Each database transformation choice is properly documented using format:
    * `TRANSFORMATION APPLIED: <NAME and DESCRIPTION OF TRANSFORMATION>`
    * `REASONING BEHIND: <WHY YOU DID IT>`
    * `EXPECTED RESULT: <WHAT IS THE (EXPECTED) RESULT OF RUNNING QUERIES GIVEN THIS TRANSFORMATION>`

</font>


**Initial data setup:**

Before starting on the queries below review the data and look to adjust the schema for the typical use case described below.

1) The most typical use case for the database is to show information relating to a property listing to a customer. This is done by a query to the database which returns one of the listing documents. Currently a lot of time is spent when a listing is retrieved from the database to show to a customer. Decide what information should be returned in a typical query and optimise the structure for this use case. For example, we typically only want a sample of reviews but not all reviews (although all reviews ), the customer does not need to know past transaction data, etc. Update the document schema for this typical use case. This may involve the creation of new collections and documents.  

2) Review the data for any errors (such as transactions that don’t fit the listing) or inappropriate duplication and clean up as appropriate. 


<font size="6">2. Uses for the database</font>

<font size="4">Different AirBNB departments require different analytics from our common database.
Here are the list of all specific questions from different departments: 

**Standard Dificulty Questions:**

3)	Once per month we like to reward hosts with recognition. Pick three superhosts who have at least two property listings that can accommodate more than four people?

4)	One of employees is thinking of buying a property to rent out. Which bed type is most common in the listings that have waterfront and a dishwasher in New York?

5)	We are thinking of identifying someone to hire to write review for us professionally. What is the name of the reviewer who left the longest review in New York?

6)	We are thinking of trying to assess the security of different areas based on the security deposit required. What is the biggest and smallest difference between the price and deposit for security per number of visitors staying at the property?

7)	We want to identify areas by whether they are typically used for short breaks, like weekend mini breaks, or whether they are more suitable for long trips. We will use this information to target advertising of different customers. It is not expected this information will change much over time so we won’t look to update it we just would like a current view. What is the average duration of stay (in nights) per type of property per city (you can use the maximum_nights to measure length of stays)? For each property type return the city with the highest and lowest average value.

**Advanced Dificulty Questions (Remember to consider how to optimise the database for these queries):**

8)	We want to have a new webpage for hosts when setting up their account. It will list suggested typical amenities. This data will need to be available every time a host registers a property but is not expected to change very much. The starting point for the list will be all unique amenities currently listed in properties (across all documents). Optimise the database for this use case and show how the data should be queried.

9)	We want to start tracking our reviewers better. We want to create a webpage that shows the top 20 reviewers and the count of the number of reviews of each of these reviewers. This webpage should be kept up to date. It should also have a link to return the number of reviews for a given reviewer ID or Name (show how to query for number of reviews by ID or query quickly).


10)	For each property we store review scores across different metrics (accuracy, check-in, cleanliness etc). We are thinking we may soon add more metrics, although we don’t know what these will be. We want to be able to easily query the average score across all of these metrics, including any new metrics that might be added without changing the query. Adjust the data model so this can be done and show the query for an example property.

11)	We wish to be able to have better access to information about transaction, we wish to develop a search engine that can calculate the average value of transactions in a given period of time quickly for a given property.


12)	We wish to have a summary webpage that displays information about our top destinations. This webpage should display for each of the top 10 cities some basic information about our operations in the area (number of properties by type for example, average price by type) but you can choose the metrics. For each of the top 10 cities it should also provide some basic information about the top 3 properties in each city (price, number of review, whatever you think useful) to show an example of the properties available in the area. We would like to keep this webpage up to date as information changes.

**Database updates:**

After you have completed the above tasks and have optimised your database show how you would complete each of the updates below. You can create whatever fictional data you like for the below. Remeber to cosider how to prevent any data you have previously created from becoming stale.

13)	Add a new property, this property should have a new host, and should be located in one of the top 10 cities. The host selects the top 10 most common amenities to be listed for the property.

14)	Add a new review to this property, the review should be from one of our top 20 reviewers.

15)	Add a new review metric called x_factor to the new document and give a score of 10. Show that the average across all metrics is correctly calculated for this listing, with the query you previously developed.


# Setup

1. run Jupyter 
2. run Docker
3. create MongoDB container in Command Prompt: make sure you don't have 'leftover' container from previous runs

        docker run --name mongodb -d -e MONGO_INITDB_ROOT_USERNAME=AzureDiamond -e MONGO_INITDB_ROOT_PASSWORD=hunter2 -p 27017:27017 mongo

4. run Studio3T

5. create New Connection OR reconnect to existing Connection:

    5.A	In Studio3T create Connection:
            a.	Press Connection -> New Connection
            b.	Insert credentials into URI field: mongodb://AzureDiamond:hunter2@localhost:27017
            c.	Press Test Connection
            d.	Assign a name to the Connection (top empty line) -> Save
            e.	Press Connect
            
    5.B In Studio3T reconnect to Connection:
            a. press Connect (top left corner)
            b. choose MongoDB connection  -> press Connect (MongoDB container must be runnning by this time)
            
6.	In Studio3T import the Database:
            a.	Press Import
            b.	Choose BSON mongodump archive 
            c.	Find your database path
            d.	Select All file formats and choose the database file ‘sampledata.archive’
            e.	Press Run: be patient while the database loads
            f.	Inspect the collections and documents

Done!

In [1]:
# Python Connector

!pip install pymongo
# or #!conda install -y pymongo

from datetime import datetime
from pprint import pprint
import time
from bson.objectid import ObjectId

from pymongo import MongoClient

user="AzureDiamond"
password="hunter2"
host="localhost"
port="27017"
protocol="mongodb"

client = MongoClient(f"{protocol}://{user}:{password}@{host}:{port}")

# Database check
db = client.sample_airbnb 
print(f"Database info: {db}\n")
db.name 

Database info: Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'sample_airbnb')



'sample_airbnb'

# Loading and Inspecting database


In [2]:
# Collections are inside our Database 'sample_analytics'

collection_list = db.list_collection_names()

print(f"The database contains {len(collection_list)} collections")
print(f"All collections: {collection_list[0:]}")
print(f"Collection {collection_list[0]} contains {db[collection_list[0]].count_documents({})} documents")

The database contains 7 collections
All collections: ['Customers', 'listingsAndReviews_new', 'listings_Mar_2019', 'reviewers', 'Reviews', 'listingsAndReviews', 'typical_amenities']
Collection Customers contains 4498 documents


[PyMongo documentation](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html)

In [3]:
pprint(db.listingsAndReviews_new.find_one())

{'_id': '10006546',
 'access': 'We are always available to help guests. The house is fully '
           'available to guests. We are always ready to assist guests. when '
           'possible we pick the guests at the airport.  This service transfer '
           'have a cost per person. We will also have service "meal at home" '
           'with a diverse menu and the taste of each. Enjoy the moment!',
 'accommodates': 8,
 'address': {'country': 'Portugal',
             'country_code': 'PT',
             'government_area': 'Cedofeita, Ildefonso, Sé, Miragaia, Nicolau, '
                                'Vitória',
             'location': {'coordinates': [-8.61308, 41.1413],
                          'is_location_exact': False,
                          'type': 'Point'},
             'market': 'Porto',
             'street': 'Porto, Porto, Portugal',
             'suburb': ''},
 'amenities': ['TV',
               'Cable TV',
               'Wifi',
               'Kitchen',
              

### Question 1

### Question 1
The most typical use case for the database is to show information relating to a property listing to a customer. This is done by a query to the database which returns one of the listing documents. Currently a lot of time is spent when a listing is retrieved from the database to show to a customer. __Decide what information should be returned in a typical query and optimise the structure for this use case. For example, we typically only want a sample of reviews but not all reviews (although all reviews ), the customer does not need to know past transaction data, etc. Update the document schema for this typical use case. This may involve the creation of new collections and documents.__

In [4]:
# Run this cell in case there is the need to delete the collections created for this answer
#db.Customers.drop()
#db.Reviews.drop()

In [5]:
# To create a new collection that contains the specified information from "listingsAndReviews_new", we will use an aggreation pipeline that will project
# the desired fields to a new collection, "Customers", by using the $out operator.
# In this case, we want to include information related to a listing that would be relevant to a customer to see. This will exclude information, for
# instnce, about detailed reviews (only the overall scores will be displayed) and past transaction data.
db.listingsAndReviews_new.aggregate([
    {"$project" : {"_id": 1,
                   "access": 1,
                   "accommodates": 1,
                   "address": 1,
                   "amenities": 1,
                   "availability": 1,
                   "bathrooms": 1,
                   "bed_type": 1,
                   "bedrooms": 1,
                   "beds": 1,
                   "cancellation_policy": 1,
                   "cleaning_fee": 1,
                   "description": 1,
                   "extra_people": 1,
                   "guests_included": 1,
                   "host_about": 1,
                   "host_id": 1,
                   "host_identity_verified": 1,
                   "host_is_superhost": 1,
                   "host_listings_count": 1,
                   "host_location": 1,
                   "host_name": 1,
                   "host_picture_url": 1,
                   "host_response_rate": 1,
                   "host_response_time": 1,
                   "host_url": 1,
                   "house_rules": 1,
                   "images": 1,
                   "interaction": 1,
                   "last_review": 1,
                   "listing_url": 1,
                   "maximum_nights": 1,
                   "minimum_nights": 1,
                   "name": 1,
                   "neighborhood_overview": 1,
                   "notes": 1,
                   "number_of_reviews": 1,
                   "price": 1,
                   "property_type": 1,
                   "review_scores": 1,
                   "room_type": 1,
                   "security_deposit": 1,
                   "space": 1,
                   "summary": 1,
                   "transit": 1
                  }},
    {"$out": "Customers"}])

In [6]:
db.Customers.find_one()

{'_id': '10006546',
 'listing_url': 'https://www.airbnb.com/rooms/10006546',
 'name': 'Ribeira Charming Duplex',
 'summary': 'Fantastic duplex apartment with three bedrooms, located in the historic area of Porto, Ribeira (Cube) - UNESCO World Heritage Site. Centenary building fully rehabilitated, without losing their original character.',
 'space': 'Privileged views of the Douro River and Ribeira square, our apartment offers the perfect conditions to discover the history and the charm of Porto. Apartment comfortable, charming, romantic and cozy in the heart of Ribeira. Within walking distance of all the most emblematic places of the city of Porto. The apartment is fully equipped to host 8 people, with cooker, oven, washing machine, dishwasher, microwave, coffee machine (Nespresso) and kettle. The apartment is located in a very typical area of the city that allows to cross with the most picturesque population of the city, welcoming, genuine and happy people that fills the streets with h

In [7]:
# Now, we will do the same for data related to reviews
# To create a new collection that contains the specified information from "listingsAndReviews_new", we will use an aggreation pipeline that will project
# the desired fields to a new collection, "Reviews", by using the $out operator.
# Here, we want to show more detailed information about the reviews. First, considering that "reviews" are inserted into the listingsAndReviews_new
# collection a list of documents, we need to unwind them, that is, extract them so that each review is seen as a single document along with the other
# fields. Then, we only have to select the fields we are in interested in - in this case, all the ones that are available from the reviews.
db.listingsAndReviews_new.aggregate([
    {"$unwind": "$reviews"},
    {"$project" : {"_id": "$reviews._id",
                   "listing_id": "$reviews.listing_id",
                   "date": "$reviews.date",
                   "reviewer_id": "$reviews.reviewer_id",
                   "reviewer_name": "$reviews.reviewer_name",
                   "comment": "$reviews.comments"
                  }},
    {"$out": "Reviews"}])

In [8]:
db.Reviews.find_one()

{'_id': '58663741',
 'listing_id': '10006546',
 'date': datetime.datetime(2016, 1, 3, 5, 0),
 'reviewer_id': '51483096',
 'reviewer_name': 'Cátia',
 'comment': 'A casa da Ana e do Gonçalo foram o local escolhido para a passagem de ano com um grupo de amigos. Fomos super bem recebidos com uma grande simpatia e predisposição a ajudar com qualquer coisa que fosse necessário.\r\nA casa era ainda melhor do que parecia nas fotos, totalmente equipada, com mantas, aquecedor e tudo o que pudessemos precisar.\r\nA localização não podia ser melhor! Não há melhor do que acordar de manhã e ao virar da esquina estar a ribeira do Porto.'}

### Question 2

We'll look for imputation errors or inconsistencies that might exist in the database.

1. **Zero Values for "beds", "bathrooms", or "price":**
   - We will analyze records where "beds", "bathrooms", or "price" is 0. Retaining such records may not be ideal and could indicate data entry errors or missing information.

2. **Value Counts and Data Inconsistencies:**
   - **2.1. "maximum_nights" field**
   - **2.2. "minimum_nights" field**
   - **2.3. Duplicates in the "id" field**
   - **2.4. "summary" field**
   - **2.5. "description" field**
   - **2.6. "notes" field**
   - **2.7. "access" field**
   - **2.8. "amenities" field**
   - **2.9. "accommodates" field**
   - **2.10. "bathrooms" field**
   - **2.11. "bedrooms" field**
   - **2.12. "bed" field**
   - **2.13. "extra_people" field**
   - **2.14. "guests_included" field**
   - **2.15. "host_identity_verified" field**
   - **2.16. "host_is_superhost" field**
   - **2.17. "host_listings_count" field**
   - **2.18. "host_name" field**
   - **2.19. "price" field**
   - **2.20. "property_type" field**
   - **2.21. "room_type" field**
   - **2.22. "cleaning_fee" field**

3. **Records with Inconsistent Guest Counts:**
   - We will consider removing records where the number of guests included exceeds the accommodation capacity. This could indicate data entry errors or inconsistencies in the dataset.


### 2.1. Value of 0 for "beds", "bathrooms", or "price"

In [9]:
zero_values = db.Customers.aggregate([

# Here we filter documents where beds, bathroom and price contains a value of 0
    {"$match": {"$or": [{"beds": 0}, {"bathrooms": 0}, {"price": 0}]}},

# Then we group the selected documents into one group, that is represented by the _id value of 0, then the sum operator calculates the total count of documents in this group, that match our conditions.   
    {"$group": {"_id": 0, "count": {"$sum": 1}}}
    
])
pprint(list(zero_values))

[{'_id': 0, 'count': 43}]


In [10]:
# Now we can delete the records, where the condition we defined above happens. 
db.Customers.delete_many({"$or": [{"beds": 0}, {"bathrooms": 0}, {"price": 0}]})

DeleteResult({'n': 43, 'ok': 1.0}, acknowledged=True)

### 2.1. Maximum_nights

The goal is to find if there are extreme values, in this case we would like to analize the highest value and also the most common one.

In [11]:
type(db.Customers.find_one().get("maximum_nights"))

str

In [12]:
value_counts = db.Customers.aggregate([
# We need to convert the maximum numbers of nights to a integer since there are records that are not integers.
    {"$project": {"maximum_nights_to_int": {"$toInt": "$maximum_nights"}}},

# Here we group by the field we want to analyze, this will be a process repeated a few times on this exercise. We count each time a value appears in the collection.
    {"$group": {"_id": "$maximum_nights_to_int", "count": {"$sum": 1}}},

# We sort the values in descending order, because it will become easier to see the high values.
    {"$sort": {"_id": -1}},

# The goal here would be to increave readabillity
    {"$project": {"_id":0, "Maximum Number of Nights": "$_id", "Count": "$count"}}
])

pprint(list(value_counts))

[{'Count': 3, 'Maximum Number of Nights': 2147483647},
 {'Count': 1, 'Maximum Number of Nights': 1234567890},
 {'Count': 1, 'Maximum Number of Nights': 333333},
 {'Count': 3, 'Maximum Number of Nights': 10000},
 {'Count': 1, 'Maximum Number of Nights': 5000},
 {'Count': 1, 'Maximum Number of Nights': 2800},
 {'Count': 1, 'Maximum Number of Nights': 1825},
 {'Count': 1, 'Maximum Number of Nights': 1250},
 {'Count': 1, 'Maximum Number of Nights': 1126},
 {'Count': 3137, 'Maximum Number of Nights': 1125},
 {'Count': 93, 'Maximum Number of Nights': 1124},
 {'Count': 7, 'Maximum Number of Nights': 1123},
 {'Count': 1, 'Maximum Number of Nights': 1121},
 {'Count': 13, 'Maximum Number of Nights': 1120},
 {'Count': 1, 'Maximum Number of Nights': 1117},
 {'Count': 2, 'Maximum Number of Nights': 1111},
 {'Count': 1, 'Maximum Number of Nights': 1110},
 {'Count': 1, 'Maximum Number of Nights': 1109},
 {'Count': 4, 'Maximum Number of Nights': 1100},
 {'Count': 3, 'Maximum Number of Nights': 1095},


We noticed that there are values really high, resulting in ``maximum nights`` of over 3 years. We believe the values are high, but since we have 3137 records with a value of 1125, we would be deleting a great amount of data. We decided that the best option would be to delete values above the 1125 days threshold.  

We can't forget that ``maximum nights`` is not an integer, so we need to use ``parseInt`` to convert it to an integer. 

In [13]:
result = db.Customers.find({
# Find where the maximum nights field is greater than 1125
    "$where": "parseInt(this.maximum_nights) > 1125"
}, 
# Just show the maximum nights field
{"_id": 0, "maximum_nights": 1})


result = db.Customers.delete_many({
    "$where": "parseInt(this.maximum_nights) > 1125"
})

pprint(f"{result.deleted_count} documents were deleted from database.")

'13 documents were deleted from database.'


### 2.2. Minimum_nights

We want to do something similar has above, were we analyze the values we have.

In [14]:
value_counts = db.Customers.aggregate([
# We need to convert the minimum numbers of nights to a integer since there are records that are not integers.
    {"$project": {"minimum_nights_to_int": {"$toInt": "$minimum_nights"}}},

# Here we group by the field we want to analyze, this will be a process repeated a few times on this exercise. We count each time a value appears in the collection.
    {"$group": {"_id": "$minimum_nights_to_int", "count": {"$sum": 1}}},

# We sort the values in descending order, because it will become easier to see the high values.
    {"$sort": {"_id": -1}},

# The goal here would be to increave readabillity
    {"$project": {"_id":0, "Minimum Number of Nights": "$_id", "Count": "$count"}}
])

pprint(list(value_counts))

[{'Count': 2, 'Minimum Number of Nights': 365},
 {'Count': 1, 'Minimum Number of Nights': 300},
 {'Count': 1, 'Minimum Number of Nights': 200},
 {'Count': 12, 'Minimum Number of Nights': 180},
 {'Count': 1, 'Minimum Number of Nights': 179},
 {'Count': 1, 'Minimum Number of Nights': 160},
 {'Count': 4, 'Minimum Number of Nights': 120},
 {'Count': 1, 'Minimum Number of Nights': 115},
 {'Count': 1, 'Minimum Number of Nights': 100},
 {'Count': 1, 'Minimum Number of Nights': 96},
 {'Count': 12, 'Minimum Number of Nights': 90},
 {'Count': 1, 'Minimum Number of Nights': 80},
 {'Count': 15, 'Minimum Number of Nights': 60},
 {'Count': 1, 'Minimum Number of Nights': 50},
 {'Count': 2, 'Minimum Number of Nights': 45},
 {'Count': 1, 'Minimum Number of Nights': 40},
 {'Count': 1, 'Minimum Number of Nights': 35},
 {'Count': 79, 'Minimum Number of Nights': 32},
 {'Count': 46, 'Minimum Number of Nights': 31},
 {'Count': 114, 'Minimum Number of Nights': 30},
 {'Count': 25, 'Minimum Number of Nights': 2

After analysing, we believe there are no extreme/unrealistic values. The highest value is 365, and since we assumed that long stays of 3 years were acceptable, we could say that for these long stays, some host ask for at least 1 year of stay.  

This being said, we will not remove any records here.

### 2.3. Duplicates in the "id" field

We also want to make sure there are duplicates in ID.

In [15]:
duplicated_id = db.Customers.aggregate([

    # Grouping by the field "id" and counting how many times each id appears in the collection listing_customer
    {"$group": {"_id": "$_id", "Count": {"$sum": 1}}},
    
    # Show only if there are duplicates (greater than 1)
    {"$match": {"Count": {"$gt": 1}}}])

pprint(list(duplicated_id))

[]


Perfect no duplicated ID's!

### 2.4. Summary

We want to analyze if this field is missing. We believe that summary is important to have values, but we also can be flexible, so our decision will be done together with description, when we get there.

But we also want to analyze if there are duplicated records.

In [16]:
missing_summary = db.Customers.aggregate([

# Here we find documents where summary does not exist or is null or contians one of the "values" on the list we defined bellow.
    {"$match": {"$or": [{"summary": {"$exists": False}}, {"summary": {"$in": [".", " ", "  ", "?",""]}}]}},

    {"$project": {"summary": 1}}
])

pprint(list(missing_summary))

[{'_id': '1003530', 'summary': ''},
 {'_id': '10133554', 'summary': ''},
 {'_id': '10199760', 'summary': ''},
 {'_id': '1022200', 'summary': ''},
 {'_id': '1036027', 'summary': ''},
 {'_id': '1038163', 'summary': ''},
 {'_id': '1042446', 'summary': ''},
 {'_id': '1068505', 'summary': ''},
 {'_id': '1073607', 'summary': ''},
 {'_id': '1077686', 'summary': ''},
 {'_id': '1079887', 'summary': ''},
 {'_id': '1090153', 'summary': ''},
 {'_id': '1098211', 'summary': ''},
 {'_id': '1117706', 'summary': ''},
 {'_id': '1132409', 'summary': ''},
 {'_id': '1144090', 'summary': ''},
 {'_id': '1163119', 'summary': ''},
 {'_id': '1182475', 'summary': ''},
 {'_id': '1195977', 'summary': ''},
 {'_id': '1209353', 'summary': ''},
 {'_id': '1215226', 'summary': ''},
 {'_id': '121861', 'summary': ''},
 {'_id': '1227759', 'summary': ''},
 {'_id': '1229106', 'summary': ''},
 {'_id': '1290112', 'summary': ''},
 {'_id': '1294944', 'summary': ''},
 {'_id': '1310308', 'summary': ''},
 {'_id': '1332929', 'summar

We can see there are a few missing values in summary, we will keep them for now, and then on details pair this discovery to take actions.  

Now let's check for duplicated values, taking id into account.

In [17]:
duplicates_summary = db.Customers.aggregate([

# We group the values by summary and count how many times each summary appears in the collection.
    {"$group": {"_id": "$summary", "count": {"$sum": 1}}},

# We only want to see duplicated values, so we ask for a count greater than 1.
    {"$match": {"count": {"$gt": 1}}},

# Sum the number of duplicated values.
    {"$group": {"_id": None, "Number of duplicated values": {"$sum": 1}}},

    {"$project": {"_id": 0, "Number of duplicated values": 1}}
])

pprint(list(duplicates_summary))

[{'Number of duplicated values': 34}]


We discovered that we have 34 duplicates. Let's analyze our options. 

We think that some hosts might have several houses that are similar to each other, for example, a host owns two apartments on the same building, the odds that these summaries are the same is very high.  

Another perspective would be that different hosts that have similar houses, will give the same summary as it's neighboor if he also rents, for example, if two neighboor host rent, the apartments are the same, so to chances one copies the other one, are also high.  

Based on both these options we decided to not remove the records, since there were not many.

### 2.5. Description

We want to check here, if both summary and description are missing, and then drop, because this doesn't give information to our guests.

In [18]:
# We used the same code as above, with small changes.
description_and_summary_dup = db.Customers.aggregate([

    {"$match": {"$and": [{"$or": [{"summary": {"$exists": False}}, {"summary": {"$in": [".", " ", "  ", "?",""]}}]}, 
                         {"$or": [{"description": {"$exists": False}}, {"description": {"$in": [".", " ", "  ", "?",""]}}]}]}},

    {"$project": {"summary": 1, "description": 1}}
])

pprint(list(description_and_summary_dup))

[{'_id': '10199760', 'description': '', 'summary': ''},
 {'_id': '15908244', 'description': '', 'summary': ''},
 {'_id': '15949042', 'description': '', 'summary': ''},
 {'_id': '19830476', 'description': '', 'summary': ''},
 {'_id': '19830549', 'description': '', 'summary': ''},
 {'_id': '19967176', 'description': '', 'summary': ''},
 {'_id': '21822223', 'description': '', 'summary': ''},
 {'_id': '24505019', 'description': '', 'summary': ''},
 {'_id': '24740074', 'description': '', 'summary': ''},
 {'_id': '25150521', 'description': '', 'summary': ''},
 {'_id': '25484442', 'description': '', 'summary': ''},
 {'_id': '25939348', 'description': '', 'summary': ''},
 {'_id': '26008844', 'description': '', 'summary': ''},
 {'_id': '26044607', 'description': '', 'summary': ''},
 {'_id': '26060837', 'description': '', 'summary': ''},
 {'_id': '26064830', 'description': '', 'summary': ''},
 {'_id': '26242605', 'description': '', 'summary': ''},
 {'_id': '26273293', 'description': '', 'summary

In [19]:
result = db.Customers.delete_many(
    {
        "$and": [
            {"$or": [{"summary": {"$exists": False}},
                    {"summary": {"$in": [".", " ", "  ", "?", ""]}},]},
                    
            {"$or": [
                    {"description": {"$exists": False}},
                    {"description": {"$in": [".", " ", "  ", "?", ""]}},]},]})

pprint(f"{result.deleted_count} documents were deleted from database.")

'95 documents were deleted from database.'


### 2.6. Notes

We want to check if there are values were notes is missing, but we likely will not delete the records, since notes is just some aditional information the host could provide. 

In [20]:
missing_notes = db.Customers.aggregate([

    {"$match": {"$or": [{"notes": {"$exists": False}}, {"notes": {"$in": [".", " ", "  ", "?",""]}}]}},

    {"$project": {"notes": 1}}
])

pprint(list(missing_notes))

[{'_id': '1001265', 'notes': ''},
 {'_id': '10021707', 'notes': ''},
 {'_id': '10030955', 'notes': ''},
 {'_id': '10038496', 'notes': ''},
 {'_id': '10047964', 'notes': ''},
 {'_id': '10057447', 'notes': ''},
 {'_id': '10057826', 'notes': ''},
 {'_id': '10059244', 'notes': ''},
 {'_id': '10059872', 'notes': ''},
 {'_id': '10066928', 'notes': ''},
 {'_id': '10069642', 'notes': ''},
 {'_id': '10082307', 'notes': ''},
 {'_id': '10082422', 'notes': ''},
 {'_id': '10083468', 'notes': ''},
 {'_id': '10096773', 'notes': ''},
 {'_id': '10115921', 'notes': ''},
 {'_id': '10116256', 'notes': ''},
 {'_id': '10116578', 'notes': ''},
 {'_id': '10117617', 'notes': ''},
 {'_id': '10120414', 'notes': ''},
 {'_id': '10133350', 'notes': ''},
 {'_id': '10133554', 'notes': ''},
 {'_id': '10140368', 'notes': ''},
 {'_id': '10166883', 'notes': ''},
 {'_id': '10184012', 'notes': ''},
 {'_id': '10186755', 'notes': ''},
 {'_id': '10201975', 'notes': ''},
 {'_id': '10220130', 'notes': ''},
 {'_id': '1022200', '

### 2.7. Access

Access is not a manditory field, since the host provides the exact locations, and access is just used to give additional information when needed. We will check for missing values, but will not enforce it. 

In [21]:
missing_access = db.Customers.aggregate([

    {"$match": {"$or": [{"access": {"$exists": False}}, {"access": {"$in": [".", " ", "  ", "?",""]}}]}},

    {"$project": {"access": 1}}
])

pprint(list(missing_access))

[{'_id': '10009999', 'access': ''},
 {'_id': '10021707', 'access': ''},
 {'_id': '10030955', 'access': ''},
 {'_id': '10047964', 'access': ''},
 {'_id': '10057447', 'access': ''},
 {'_id': '10059872', 'access': ''},
 {'_id': '10069642', 'access': ''},
 {'_id': '10082307', 'access': ''},
 {'_id': '10096773', 'access': ''},
 {'_id': '10115921', 'access': ''},
 {'_id': '10116256', 'access': ''},
 {'_id': '10116578', 'access': ''},
 {'_id': '10133350', 'access': ''},
 {'_id': '10141950', 'access': ''},
 {'_id': '10166986', 'access': ''},
 {'_id': '10186755', 'access': ''},
 {'_id': '1022200', 'access': ''},
 {'_id': '10227000', 'access': ''},
 {'_id': '10267144', 'access': ''},
 {'_id': '10269320', 'access': ''},
 {'_id': '10280433', 'access': ''},
 {'_id': '10295352', 'access': ''},
 {'_id': '10306879', 'access': ''},
 {'_id': '10317142', 'access': ''},
 {'_id': '10324377', 'access': ''},
 {'_id': '10332161', 'access': ''},
 {'_id': '10354347', 'access': ''},
 {'_id': '10359729', 'access'

### 2.8. Amenities

Amenities on the other hand, has to have a value, since when someone is renting a place, they want to know what amenties exist.  

So here, we will enforce te rule, and delete any missing values.  

Let's check for the values that exist.

In [22]:
result = db.Customers.aggregate([
    # Unwind the field 'amenities'
    {"$unwind": "$amenities" },
    # Group by the field 'amenities' and count the number of ocurrences
    {"$group": {"_id":"$amenities","Count":{"$sum":1}}},
    # Sort the amenities by the number of ocurrences in descending order
    {"$sort":{ "Count": -1}},
    # Project the 'amenity' and 'Count' fields
    {"$project":{"_id":0, "amenity":"$_id", "Count":1}}
])

pprint(list(result))

[{'Count': 5162, 'amenity': 'Wifi'},
 {'Count': 4908, 'amenity': 'Essentials'},
 {'Count': 4820, 'amenity': 'Kitchen'},
 {'Count': 4176, 'amenity': 'TV'},
 {'Count': 4114, 'amenity': 'Hangers'},
 {'Count': 3800, 'amenity': 'Hair dryer'},
 {'Count': 3776, 'amenity': 'Washer'},
 {'Count': 3601, 'amenity': 'Shampoo'},
 {'Count': 3595, 'amenity': 'Iron'},
 {'Count': 3360, 'amenity': 'Laptop friendly workspace'},
 {'Count': 3349, 'amenity': 'Air conditioning'},
 {'Count': 3196, 'amenity': 'Heating'},
 {'Count': 2883, 'amenity': 'Hot water'},
 {'Count': 2824, 'amenity': 'Smoke detector'},
 {'Count': 2452, 'amenity': 'Family/kid friendly'},
 {'Count': 2334, 'amenity': 'Dryer'},
 {'Count': 2285, 'amenity': 'Elevator'},
 {'Count': 2162, 'amenity': 'Fire extinguisher'},
 {'Count': 1856, 'amenity': 'Refrigerator'},
 {'Count': 1787, 'amenity': 'Internet'},
 {'Count': 1764, 'amenity': 'First aid kit'},
 {'Count': 1730, 'amenity': 'Bed linens'},
 {'Count': 1709, 'amenity': 'Cable TV'},
 {'Count': 16

We see that there are some weird values, so lets's also remove them.  
- 'translation missing: en.hosting_amenity_49'  
- 'translation missing: en.hosting_amenity_50'

In [23]:
missing_amenities = db.Customers.aggregate([

    {"$match": {"$or": [{"amenities": {"$exists": False}}, {"amenities": {"$in": [".", " ", "  ", "?",""]}}]}},

    {"$project": {"Amenities": 1}}
])

pprint(list(missing_amenities))

[{'_id': '1077686'},
 {'_id': '11863943'},
 {'_id': '1290112'},
 {'_id': '13145113'},
 {'_id': '13249697'},
 {'_id': '13837488'},
 {'_id': '14554642'},
 {'_id': '16622489'},
 {'_id': '19592057'},
 {'_id': '20354056'},
 {'_id': '20517090'},
 {'_id': '20744948'},
 {'_id': '2436700'},
 {'_id': '2764689'},
 {'_id': '2794928'},
 {'_id': '28002020'},
 {'_id': '2868278'},
 {'_id': '2873436'},
 {'_id': '2946022'},
 {'_id': '2964930'},
 {'_id': '31548152'},
 {'_id': '3786402'},
 {'_id': '4573398'},
 {'_id': '662403'},
 {'_id': '6663848'},
 {'_id': '7080271'},
 {'_id': '7242041'},
 {'_id': '757385'},
 {'_id': '781631'},
 {'_id': '9677123'}]


In [24]:
result = db.Customers.delete_many({
    "$or": [
        {"amenities": {"$exists": False}},
        {"amenities": {"$in": [".", " ", "  ", "?", ""]}},
        {"amenities": "translation missing: en.hosting_amenity_49"},
        {"amenities": "translation missing: en.hosting_amenity_50"}
    ]
})

print(result.deleted_count, "documents deleted.")

875 documents deleted.


### 2.9. Accomodates

We want to check, just like before, if there are any strange or extreme values, that would make sense to remove

In [25]:
# The code is basically the same as done before
value_counts = db.Customers.aggregate([

    {"$group": {"_id": "$accommodates", "Count": {"$sum": 1}}},

    {"$sort": {"_id": -1}},

    {"$project": {"Accommodates": "$_id", "Count": 1, "_id":0}}
])

pprint(list(value_counts))

[{'Accommodates': 16, 'Count': 23},
 {'Accommodates': 15, 'Count': 2},
 {'Accommodates': 14, 'Count': 11},
 {'Accommodates': 13, 'Count': 6},
 {'Accommodates': 12, 'Count': 31},
 {'Accommodates': 11, 'Count': 7},
 {'Accommodates': 10, 'Count': 62},
 {'Accommodates': 9, 'Count': 27},
 {'Accommodates': 8, 'Count': 182},
 {'Accommodates': 7, 'Count': 72},
 {'Accommodates': 6, 'Count': 468},
 {'Accommodates': 5, 'Count': 237},
 {'Accommodates': 4, 'Count': 1031},
 {'Accommodates': 3, 'Count': 477},
 {'Accommodates': 2, 'Count': 1500},
 {'Accommodates': 1, 'Count': 393}]


Nothing extreme, so we will not do any changes.

### 2.10. Bathrooms

We want to check, just like before, if there are any strange or extreme values, that would make sense to remove

In [26]:
# The code is basically the same as done before
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$bathrooms", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"Bathrooms": "$_id", "Count":  "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Bathrooms': Decimal128('16.0'), 'Count': 1},
 {'Bathrooms': Decimal128('9.0'), 'Count': 1},
 {'Bathrooms': Decimal128('8.0'), 'Count': 5},
 {'Bathrooms': Decimal128('7.0'), 'Count': 6},
 {'Bathrooms': Decimal128('6.0'), 'Count': 4},
 {'Bathrooms': Decimal128('5.5'), 'Count': 2},
 {'Bathrooms': Decimal128('5.0'), 'Count': 11},
 {'Bathrooms': Decimal128('4.5'), 'Count': 8},
 {'Bathrooms': Decimal128('4.0'), 'Count': 30},
 {'Bathrooms': Decimal128('3.5'), 'Count': 23},
 {'Bathrooms': Decimal128('3.0'), 'Count': 124},
 {'Bathrooms': Decimal128('2.5'), 'Count': 60},
 {'Bathrooms': Decimal128('2.0'), 'Count': 682},
 {'Bathrooms': Decimal128('1.5'), 'Count': 181},
 {'Bathrooms': Decimal128('1.0'), 'Count': 3374},
 {'Bathrooms': Decimal128('0.5'), 'Count': 11},
 {'Bathrooms': None, 'Count': 6}]


At first, we found strange that the number of bathrooms can be decimal, but after some research, we discovered that airbnb defines 1 bathroom as having a sink, bathtub, shower and toilet, while a 0,5 bathroom would only include toilet and sink.  


https://community.withairbnb.com/t5/Advice-on-your-space/How-to-calculate-Bathrooms/m-p/1439618/highlight/true

### 2.11. Bedrooms

We want to check, just like before, if there are any strange or extreme values, that would make sense to remove

In [27]:
# The code is basically the same as done before
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$bedrooms", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"Bedrooms": "$_id", "Count":  "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Bedrooms': 20, 'Count': 1},
 {'Bedrooms': 15, 'Count': 1},
 {'Bedrooms': 10, 'Count': 2},
 {'Bedrooms': 9, 'Count': 2},
 {'Bedrooms': 8, 'Count': 3},
 {'Bedrooms': 7, 'Count': 7},
 {'Bedrooms': 6, 'Count': 15},
 {'Bedrooms': 5, 'Count': 34},
 {'Bedrooms': 4, 'Count': 149},
 {'Bedrooms': 3, 'Count': 390},
 {'Bedrooms': 2, 'Count': 976},
 {'Bedrooms': 1, 'Count': 2549},
 {'Bedrooms': 0, 'Count': 396},
 {'Bedrooms': None, 'Count': 4}]


### 2.12. Bed

We want to check, just like before, if there are any strange or extreme values, that would make sense to remove

In [28]:
# The code is basically the same as done before
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$beds", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"Beds": "$_id", "Count":  "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Beds': 25, 'Count': 1},
 {'Beds': 18, 'Count': 1},
 {'Beds': 16, 'Count': 2},
 {'Beds': 15, 'Count': 2},
 {'Beds': 14, 'Count': 2},
 {'Beds': 13, 'Count': 1},
 {'Beds': 12, 'Count': 5},
 {'Beds': 11, 'Count': 3},
 {'Beds': 10, 'Count': 13},
 {'Beds': 9, 'Count': 10},
 {'Beds': 8, 'Count': 28},
 {'Beds': 7, 'Count': 39},
 {'Beds': 6, 'Count': 104},
 {'Beds': 5, 'Count': 157},
 {'Beds': 4, 'Count': 351},
 {'Beds': 3, 'Count': 596},
 {'Beds': 2, 'Count': 1194},
 {'Beds': 1, 'Count': 2012},
 {'Beds': None, 'Count': 8}]


### 2.13. Extra People

Extra is a fee the host can decide, if someone bring extra people to the booking. 

In [29]:
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$extra_people", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"extra_people": "$_id", "Count": "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Count': 3, 'extra_people': Decimal128('1000.00')},
 {'Count': 1, 'extra_people': Decimal128('968.00')},
 {'Count': 2, 'extra_people': Decimal128('900.00')},
 {'Count': 1, 'extra_people': Decimal128('800.00')},
 {'Count': 1, 'extra_people': Decimal128('769.00')},
 {'Count': 1, 'extra_people': Decimal128('600.00')},
 {'Count': 1, 'extra_people': Decimal128('584.00')},
 {'Count': 2, 'extra_people': Decimal128('560.00')},
 {'Count': 1, 'extra_people': Decimal128('550.00')},
 {'Count': 1, 'extra_people': Decimal128('542.00')},
 {'Count': 1, 'extra_people': Decimal128('530.00')},
 {'Count': 1, 'extra_people': Decimal128('506.00')},
 {'Count': 7, 'extra_people': Decimal128('500.00')},
 {'Count': 1, 'extra_people': Decimal128('350.00')},
 {'Count': 2, 'extra_people': Decimal128('314.00')},
 {'Count': 10, 'extra_people': Decimal128('300.00')},
 {'Count': 1, 'extra_people': Decimal128('280.00')},
 {'Count': 1, 'extra_people': Decimal128('277.00')},
 {'Count': 1, 'extra_people': Decimal128('27

The values seem normal. Most of the hosts dont actually define a fee.

### 2.14. Guest Included

In [30]:
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$guests_included", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"guest_included": "$_id", "Count": "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Count': 3, 'guest_included': Decimal128('16')},
 {'Count': 2, 'guest_included': Decimal128('15')},
 {'Count': 2, 'guest_included': Decimal128('13')},
 {'Count': 7, 'guest_included': Decimal128('12')},
 {'Count': 17, 'guest_included': Decimal128('10')},
 {'Count': 6, 'guest_included': Decimal128('9')},
 {'Count': 30, 'guest_included': Decimal128('8')},
 {'Count': 14, 'guest_included': Decimal128('7')},
 {'Count': 121, 'guest_included': Decimal128('6')},
 {'Count': 57, 'guest_included': Decimal128('5')},
 {'Count': 340, 'guest_included': Decimal128('4')},
 {'Count': 141, 'guest_included': Decimal128('3')},
 {'Count': 921, 'guest_included': Decimal128('2')},
 {'Count': 2868, 'guest_included': Decimal128('1')}]


No extreme values, so we keep everything

### 2.15. Host Identity Verified

In [31]:
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$host_identity_verified", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"host_identity_verified": "$_id", "Count": "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Count': 1489, 'host_identity_verified': True},
 {'Count': 3040, 'host_identity_verified': False}]


In our opinion, this should not be allowed, since a host not being verified means that no identification was provides or no manditory documents. On the other hand, we decided to keep the values, since there over 3 000 records with no verification.

### 2.16. Host is Superhost

In [32]:
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$host_is_superhost", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"host_is_superhost": "$_id", "Count": "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Count': 823, 'host_is_superhost': True},
 {'Count': 3706, 'host_is_superhost': False}]


Most of our dataset is not a superhost, this would be expected since the majority is not even verified.

### 2.17. Host Listings Count

In [33]:
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$host_listings_count", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"host_listings_count": "$_id", "Count": "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Count': 11, 'host_listings_count': 1198},
 {'Count': 1, 'host_listings_count': 799},
 {'Count': 3, 'host_listings_count': 508},
 {'Count': 2, 'host_listings_count': 472},
 {'Count': 7, 'host_listings_count': 429},
 {'Count': 1, 'host_listings_count': 372},
 {'Count': 2, 'host_listings_count': 324},
 {'Count': 2, 'host_listings_count': 320},
 {'Count': 6, 'host_listings_count': 294},
 {'Count': 2, 'host_listings_count': 265},
 {'Count': 9, 'host_listings_count': 256},
 {'Count': 1, 'host_listings_count': 241},
 {'Count': 5, 'host_listings_count': 239},
 {'Count': 18, 'host_listings_count': 229},
 {'Count': 3, 'host_listings_count': 226},
 {'Count': 2, 'host_listings_count': 222},
 {'Count': 9, 'host_listings_count': 203},
 {'Count': 2, 'host_listings_count': 200},
 {'Count': 1, 'host_listings_count': 187},
 {'Count': 2, 'host_listings_count': 183},
 {'Count': 1, 'host_listings_count': 177},
 {'Count': 1, 'host_listings_count': 170},
 {'Count': 7, 'host_listings_count': 169},
 {'Count

We have two host that still have no listings. We are okay with this, since it can happen to just create an account to understand how the hosting process is made.

### 2.18. Host Name

Host name is something manditory, so we would expect no missing values.

In [34]:
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$host_name", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"host_name": "$_id", "Count": "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Count': 1, 'host_name': '馨'},
 {'Count': 1, 'host_name': '香蕉宿黑金厂民宿精品酒店'},
 {'Count': 1, 'host_name': '飞飞'},
 {'Count': 2, 'host_name': '霖华'},
 {'Count': 1, 'host_name': '陈'},
 {'Count': 1, 'host_name': '锦鸿'},
 {'Count': 1, 'host_name': '蘭芳姐'},
 {'Count': 1, 'host_name': '萌'},
 {'Count': 2, 'host_name': '菁'},
 {'Count': 1, 'host_name': '茱迪'},
 {'Count': 1, 'host_name': '脆脆'},
 {'Count': 1, 'host_name': '翔茜'},
 {'Count': 1, 'host_name': '磚'},
 {'Count': 1, 'host_name': '燕芳'},
 {'Count': 1, 'host_name': '燕'},
 {'Count': 1, 'host_name': '炼金'},
 {'Count': 1, 'host_name': '洋'},
 {'Count': 1, 'host_name': '汝聰'},
 {'Count': 1, 'host_name': '昭霞'},
 {'Count': 1, 'host_name': '文杰'},
 {'Count': 2, 'host_name': '文文'},
 {'Count': 1, 'host_name': '巧'},
 {'Count': 1, 'host_name': '少蔚'},
 {'Count': 1, 'host_name': '小雨'},
 {'Count': 1, 'host_name': '小莲'},
 {'Count': 1, 'host_name': '小'},
 {'Count': 1, 'host_name': '家仪(Kay)'},
 {'Count': 1, 'host_name': '宇'},
 {'Count': 3, 'host_name': '宅一起'},
 {'Coun

In [35]:
missing_name = db.Customers.aggregate([

    {"$match": {"$or": [{"host_name": {"$exists": False}}, {"host_name": {"$in": [".", " ", "  ", "?",""]}}]}},

    {"$project": {"host_name": 1}}
])

pprint(list(missing_access))

[]


No missing values, everything is correct.

### 2.19. Price

In [36]:
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$price", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"price": "$_id", "Count": "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Count': 1, 'price': Decimal128('48842.00')},
 {'Count': 2, 'price': Decimal128('11681.00')},
 {'Count': 1, 'price': Decimal128('11190.00')},
 {'Count': 2, 'price': Decimal128('10001.00')},
 {'Count': 1, 'price': Decimal128('7203.00')},
 {'Count': 1, 'price': Decimal128('7002.00')},
 {'Count': 2, 'price': Decimal128('5595.00')},
 {'Count': 1, 'price': Decimal128('5502.00')},
 {'Count': 1, 'price': Decimal128('4828.00')},
 {'Count': 1, 'price': Decimal128('4761.00')},
 {'Count': 1, 'price': Decimal128('4745.00')},
 {'Count': 1, 'price': Decimal128('4498.00')},
 {'Count': 1, 'price': Decimal128('3726.00')},
 {'Count': 2, 'price': Decimal128('3544.00')},
 {'Count': 1, 'price': Decimal128('3499.00')},
 {'Count': 1, 'price': Decimal128('3399.00')},
 {'Count': 1, 'price': Decimal128('3301.00')},
 {'Count': 1, 'price': Decimal128('3253.00')},
 {'Count': 1, 'price': Decimal128('3250.00')},
 {'Count': 1, 'price': Decimal128('3000.00')},
 {'Count': 5, 'price': Decimal128('2999.00')},
 {'Count'

### 2.20. Property Type

In [37]:
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$property_type", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"property_type": "$_id", "Count": "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Count': 22, 'property_type': 'Villa'},
 {'Count': 84, 'property_type': 'Townhouse'},
 {'Count': 5, 'property_type': 'Tiny house'},
 {'Count': 166, 'property_type': 'Serviced apartment'},
 {'Count': 11, 'property_type': 'Resort'},
 {'Count': 1, 'property_type': 'Pension (South Korea)'},
 {'Count': 15, 'property_type': 'Other'},
 {'Count': 113, 'property_type': 'Loft'},
 {'Count': 1, 'property_type': 'Hut'},
 {'Count': 1, 'property_type': 'Houseboat'},
 {'Count': 497, 'property_type': 'House'},
 {'Count': 25, 'property_type': 'Hotel'},
 {'Count': 29, 'property_type': 'Hostel'},
 {'Count': 1, 'property_type': 'Heritage hotel (India)'},
 {'Count': 38, 'property_type': 'Guesthouse'},
 {'Count': 56, 'property_type': 'Guest suite'},
 {'Count': 8, 'property_type': 'Farm stay'},
 {'Count': 19, 'property_type': 'Cottage'},
 {'Count': 349, 'property_type': 'Condominium'},
 {'Count': 2, 'property_type': 'Chalet'},
 {'Count': 1, 'property_type': 'Castle'},
 {'Count': 8, 'property_type': 'Casa pa

In [38]:
missing_property_type = db.Customers.aggregate([

    {"$match": {"$or": [{"property_type": {"$exists": False}}, {"property_type": {"$in": [".", " ", "  ", "?",""]}}]}},

    {"$project": {"property_type": 1}}
])

pprint(list(missing_property_type))

[]


No missing values, so there should not be any problems

### 2.21. Room Type

In [39]:
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$room_type", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"room_type": "$_id", "Count": "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Count': 67, 'room_type': 'Shared room'},
 {'Count': 1475, 'room_type': 'Private room'},
 {'Count': 2987, 'room_type': 'Entire home/apt'}]


### 2.22. Cleaning Fee

In [40]:
value_counts = db.Customers.aggregate([

  {"$group": {"_id": "$cleaning_fee", "count": {"$sum": 1}}},

  {"$sort": {"_id": -1}},

  {"$project": {"cleaning_fee": "$_id", "Count": "$count", "_id":0}}
])

pprint(list(value_counts))

[{'Count': 1, 'cleaning_fee': Decimal128('2000.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('1000.00')},
 {'Count': 3, 'cleaning_fee': Decimal128('942.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('910.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('850.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('800.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('750.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('693.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('685.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('650.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('617.00')},
 {'Count': 3, 'cleaning_fee': Decimal128('600.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('599.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('596.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('580.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('578.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('575.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('567.00')},
 {'Count': 1, 'cleaning_fee': Decimal128('56

We want to update were the field is "None" to 0. 

In [41]:
cleaning_fee_update = db.Customers.update_many(

    { "cleaning_fee": None },

    { "$set": { "cleaning_fee": 0 } })

print(cleaning_fee_update.modified_count, "documents were updated.")

1253 documents were updated.


### 3. Records with Inconsistent Guest Counts

In [42]:
inconsisten_guest = db.Customers.aggregate([
    
# We need to use "$expr" operator to compare the values of the included guests with how many accommodates supports. 
  { "$match": { "$expr": { "$gt": ["$guests_included", "$accommodates"] } } },

  { "$count": "total" }
])

print(list(inconsisten_guest))

[{'total': 31}]


We decided that there were not many records, so we dropped them.

In [43]:
documents_to_delete = db.Customers.delete_many({ "$expr": { "$gt": ["$guests_included", "$accommodates"] } })

print(documents_to_delete.deleted_count, "documents were deleted.")

31 documents were deleted.


### Question 3 

In [44]:
# For this first query, we will start by filtering the documents by keeping only those that are superhosts, have at least 2 property listings and can
# accommodate more than 4 people. Then, we will select 3 customers that match the defined conditions. Finally, we will output only the relevant
# information regarding the selected hosts (including the number of listings and the people they can accommodate).
question3 = list(db.Customers.aggregate([
    {"$match": {"host_is_superhost": True,
                "host_listings_count": {"$gte": 2},
                "accommodates": {"$gt": 4}}},
    {"$limit": 3},
    {"$project": {"Host ID": "$_id",
                  "Host Name": "$host_name",
                  "Number of Listings": "$host_listings_count",
                  "People that Accomodates": "$accommodates",
                  "_id": 0}}
]))

pprint(question3)

[{'Host ID': '10548991',
  'Host Name': 'Nate',
  'Number of Listings': 3,
  'People that Accomodates': 11},
 {'Host ID': '10570041',
  'Host Name': 'Roberta (Beta) Gatti',
  'Number of Listings': 18,
  'People that Accomodates': 6},
 {'Host ID': '10635276',
  'Host Name': 'Luiz Henrique',
  'Number of Listings': 2,
  'People that Accomodates': 6}]


### Question 4

In [45]:
# Here, we will start by filtering the query so that we only keep the documents that we are interested moving forward. In this case, we want to keep
# the place that have both a Waterfront and a Dishwasher, but we only want those that are in New York. Next, we will group them by "bed_type" and sum,
# so that we attain the total number of bed types that are in places that match the previously defined conditions. Then, we will sort the results in
# desceding order and keep only the value that appears the most times, projecting the relevant information as the output.
question4 = list(db.Customers.aggregate([
    {"$match": {"amenities": {"$all": ["Waterfront", "Dishwasher"]},
                "address.market": "New York"}},
    {"$group": {"_id": "$bed_type",
                "bed_count": {"$sum": 1}}},
    {"$sort": {"bed_count": -1}},
    {"$limit": 1},
    {"$project": {"Bed Type": "$_id",
                  "Number of Beds": "$bed_count",
                  "_id": 0}}
]))

pprint(question4)

[{'Bed Type': 'Real Bed', 'Number of Beds': 1}]


### Question 5

In [46]:
# For this query, we will need to have reviews and customers together once again (since we will focus on the reviews but we also need to filter the
# address for New York). To do that, we will start by using $lookup to join the collections based on "location_id" (just "_id on the Customers
# collection). Then, we will match for reviews that were made for places in New York and where comments have been made (using the help from $exists
# https://www.mongodb.com/docs/manual/reference/operator/query/exists/). Next, we will a new field consisting of the length of the comment that was made
# (https://www.mongodb.com/docs/manual/reference/operator/aggregation/strLenCP/ and 
# https://stackoverflow.com/questions/3974985/update-mongodb-field-using-value-of-another-field), sort it by descending order according to the review
# length and keep only the review that was the longest. Finally, we will project the name of the reviewer and the length of the review that he/she made.
question5 = list(db.Reviews.aggregate([
    {"$lookup": {"from": "Customers",
                 "localField": "listing_id",
                 "foreignField": "_id",
                 "as": "Customers_NEW"}},
    {"$match": {"Customers_NEW.address.market": "New York",
                "comment": {"$exists": True}}},
    {"$addFields": {"review_length": {"$strLenCP": "$comment"}}},
    {"$sort": {"review_length": -1}},
    {"$limit": 1},
    {"$project": {"Reviewer Name": "$reviewer_name",
                  "Review Length": "$review_length",
                  "_id": 0}}
]))

pprint(question5)

[{'Review Length': 4665, 'Reviewer Name': 'Angela'}]


### Question 6

In [47]:
# Here, we will start by filtering only the listings that actually have a security deposit and can have at least one guest. Then, we will make an
# initial projection, keeping only the fields that will be relevant to our future analysis. This is also where we will calculate the absolute difference
# between the price for the listing and the security deposit that is asked for said listing. Next, we will group by the number of accommodates, as is
# asked, and find the maximum and minimum values for the differences we just calculated. We will also sort by the the number of accommodates (named as
# "_id" after the $group stage) for visualization purposes, before projecting the solution.
question6 = list(db.Customers.aggregate([
    {"$match": {"security_deposit": {"$exists": True}, "accommodates": {"$gte": 1}}},
    {"$project": {"price": 1,
                  "security_deposit": 1,
                  "dif": {"$abs": {"$subtract": ["$price", "$security_deposit"]}},
                  "address": 1,
                  "accommodates": 1,
                  "_id": 0}},
    {"$group": {"_id": "$accommodates",
                "max_dif": {"$max": "$dif"},
                "min_dif": {"$min": "$dif"}}},
    {"$sort": {"_id": 1}},
    {"$project": {"Number of Guests": "$_id",
                  "Minimum Difference": "$min_dif",
                  "Maximum Difference": "$max_dif",
                  "_id": 0}}
]))

pprint(question6)

[{'Maximum Difference': Decimal128('10749.00'),
  'Minimum Difference': Decimal128('0.00'),
  'Number of Guests': 1},
 {'Maximum Difference': Decimal128('38459.00'),
  'Minimum Difference': Decimal128('0.00'),
  'Number of Guests': 2},
 {'Maximum Difference': Decimal128('19546.00'),
  'Minimum Difference': Decimal128('3.00'),
  'Number of Guests': 3},
 {'Maximum Difference': Decimal128('29148.00'),
  'Minimum Difference': Decimal128('0.00'),
  'Number of Guests': 4},
 {'Maximum Difference': Decimal128('8501.00'),
  'Minimum Difference': Decimal128('1.00'),
  'Number of Guests': 5},
 {'Maximum Difference': Decimal128('17735.00'),
  'Minimum Difference': Decimal128('0.00'),
  'Number of Guests': 6},
 {'Maximum Difference': Decimal128('2501.00'),
  'Minimum Difference': Decimal128('0.00'),
  'Number of Guests': 7},
 {'Maximum Difference': Decimal128('7644.00'),
  'Minimum Difference': Decimal128('1.00'),
  'Number of Guests': 8},
 {'Maximum Difference': Decimal128('1350.00'),
  'Minimum D

### Question 7  

In [48]:
# For this question, we were asked for two different things: "What is the average duration of stay (in nights) per type of property per city?" and "For
# each property type, return the city with the highest and lowest average value." Let's start with the first query, where we want to find the average
# duration of stay for each property in each city. Here, we will use $match to keep only records where the "maximum_nights" field is present, but also
# where "city" is not just an empty space. Next, we will group by property and city, and we will calculate the average duration of stay. Since the field
# "maximum_nights" is deemed as a string, we will have to convert these records to integers to be able to calculate the mean. Then, we will select only
# the fields we are interested in (and round the average duration of stay to 2 decimal places) and sort by city and, within each one, by property type,
# in order to get a cleaner visualization of the results.
question7_1 = list(db.Customers.aggregate([
    {"$match": {"$expr": {"$ne": [{"$toInt": "$maximum_nights"}, None]},
                "address.market": {"$ne": ""}}},
    {"$group": {"_id": {"property_type": "$property_type", "city": "$address.market"},
                "avg_stay": {"$avg": {"$toInt": "$maximum_nights"}}}},
    {"$project": {"Property Type": "$_id.property_type",
                  "City": "$_id.city",
                  "Average Stay": {"$round": ["$avg_stay", 2]},
                  "_id": 0}},
    {"$sort": {"City": 1, "Property Type": 1}}
]))

pprint(question7_1)

[{'Average Stay': 780.0, 'City': 'Barcelona', 'Property Type': 'Aparthotel'},
 {'Average Stay': 739.93, 'City': 'Barcelona', 'Property Type': 'Apartment'},
 {'Average Stay': 683.6,
  'City': 'Barcelona',
  'Property Type': 'Bed and breakfast'},
 {'Average Stay': 1125.0,
  'City': 'Barcelona',
  'Property Type': 'Boutique hotel'},
 {'Average Stay': 1125.0,
  'City': 'Barcelona',
  'Property Type': 'Casa particular (Cuba)'},
 {'Average Stay': 768.73, 'City': 'Barcelona', 'Property Type': 'Condominium'},
 {'Average Stay': 1125.0, 'City': 'Barcelona', 'Property Type': 'Farm stay'},
 {'Average Stay': 1125.0, 'City': 'Barcelona', 'Property Type': 'Guest suite'},
 {'Average Stay': 652.5, 'City': 'Barcelona', 'Property Type': 'Guesthouse'},
 {'Average Stay': 754.67, 'City': 'Barcelona', 'Property Type': 'Hostel'},
 {'Average Stay': 863.12, 'City': 'Barcelona', 'Property Type': 'House'},
 {'Average Stay': 616.69, 'City': 'Barcelona', 'Property Type': 'Loft'},
 {'Average Stay': 1125.0, 'City': '

In [49]:
# For the second query ("For each property type, return the city with the highest and lowest average value."), the initial process is very similar, with
# identical $match and $group stages. Next, we will sort by property type in ascending order and, within each property, by average duration of stay.
# This will be useful in the following step, where we will group (again) by property type, and then find the cities that appear last and first for each 
# property type and their respective average durations of stay - these will correspond, respectively, to the cities with the biggest and lowest average 
# duration of stay. Finally, we will rename the columns in the $project stage and sort again by property type, to allow for a cleaner visualization of
# the results.
question7_2 = list(db.Customers.aggregate([
    {"$match": {"maximum_nights": {"$exists": True},
                "address.market": {"$ne": ""}}},
    {"$group": {"_id": {"property_type": "$property_type", "city": "$address.market"},
                "avg_stay": {"$avg": {"$toInt": "$maximum_nights"}}}},
    {"$sort": {"_id.property_type": 1, "avg_stay": 1}},
    {"$group": {"_id": "$_id.property_type", 
                "city_max_stay": {"$last": "$_id.city"},
                "max_stay": {"$last": "$avg_stay"},
                "city_min_stay": {"$first": "$_id.city"},
                "min_stay": {"$first": "$avg_stay"}}},
    {"$project": {"Property Type": "$_id",
                  "City with Biggest Average Stay": "$city_max_stay",
                  "Biggest Average Stay": "$max_stay",
                  "City with Lowest Average Stay": "$city_min_stay",
                  "Lowest Average Stay": "$min_stay",
                  "_id": 0}},
    {"$sort": {"Property Type": 1}}
]))

pprint(question7_2)

[{'Biggest Average Stay': 1125.0,
  'City with Biggest Average Stay': 'Montreal',
  'City with Lowest Average Stay': 'Oahu',
  'Lowest Average Stay': 60.0,
  'Property Type': 'Aparthotel'},
 {'Biggest Average Stay': 831.6567567567567,
  'City with Biggest Average Stay': 'Hong Kong',
  'City with Lowest Average Stay': 'The Big Island',
  'Lowest Average Stay': 365.0,
  'Property Type': 'Apartment'},
 {'Biggest Average Stay': 1125.0,
  'City with Biggest Average Stay': 'Sydney',
  'City with Lowest Average Stay': 'Kauai',
  'Lowest Average Stay': 30.0,
  'Property Type': 'Bed and breakfast'},
 {'Biggest Average Stay': 1125.0,
  'City with Biggest Average Stay': 'Porto',
  'City with Lowest Average Stay': 'Porto',
  'Lowest Average Stay': 1125.0,
  'Property Type': 'Boat'},
 {'Biggest Average Stay': 1125.0,
  'City with Biggest Average Stay': 'Barcelona',
  'City with Lowest Average Stay': 'Sydney',
  'Lowest Average Stay': 577.5,
  'Property Type': 'Boutique hotel'},
 {'Biggest Average S

### Question 8

In [51]:
from pymongo import DESCENDING

def compute_typical_amenities():
    # Define the aggregation pipeline to compute typical amenities
    pipeline = [
        {"$unwind": "$amenities"},  # Unwind the 'amenities' field to have one amenity per document
        {"$sortByCount": "$amenities"},  # Sort amenities by count in descending order
        {"$limit": 10},  # Limit to the first 10 amenities
        {"$project": {"_id": 0, "amenity": "$_id"}}  # Project only the amenity field
    ]
    
    # Execute the aggregation pipeline to compute typical amenities
    typical_amenities = list(db.Customers.aggregate(pipeline))
    
    # If typical_amenities is not empty, insert the results into the 'typical_amenities' collection
    if typical_amenities:
        db.typical_amenities.insert_many(typical_amenities)
    else:
        print("No typical amenities found.")

# Call the function to compute and store typical amenities
compute_typical_amenities()

# Define a function to retrieve suggested typical amenities for hosts' setup page
def get_suggested_typical_amenities():
    # Query the typical amenities collection
    typical_amenities_cursor = db.typical_amenities.find({}, {"_id": 0, "amenity": 1})
    # Extract amenities from the cursor and return them as a list
    return [amenity["amenity"] for amenity in typical_amenities_cursor]

# Call the function to get suggested typical amenities
suggested_typical_amenities = get_suggested_typical_amenities()

# Print the list of suggested typical amenities
print("Suggested typical amenities:")
for amenity in suggested_typical_amenities:
    pprint(str(amenity))

Suggested typical amenities:
'Wifi'
'Essentials'
'Kitchen'
'TV'
'Hangers'
'Washer'
'Hair dryer'
'Shampoo'
'Iron'
'Air conditioning'
'Wifi'
'Essentials'
'Kitchen'
'TV'
'Hangers'
'Washer'
'Hair dryer'
'Shampoo'
'Iron'
'Air conditioning'
'Wifi'
'Essentials'
'Kitchen'
'TV'
'Hangers'
'Washer'
'Hair dryer'
'Shampoo'
'Iron'
'Air conditioning'


### Question 9

In [58]:
# Define a new collection for reviewers
reviewers_collection = db.reviewers

# Function to find the top 20 reviewers based on review count
def find_top_reviewers():
    # Aggregation pipeline to unwind reviews, group by reviewer ID, count, sort, and limit to top 20
    pipeline = [
        {"$unwind": "$reviews"},
        {"$group": {"_id": "$reviews.reviewer_id", "review_count": {"$sum": 1}}},
        {"$sort": {"review_count": -1}},
        {"$limit": 20}
    ]
    
    # Execute the aggregation pipeline
    result = list(db.listingsAndReviews_new.aggregate(pipeline))
    return [reviewer['_id'] for reviewer in result]

# Function to update reviewers collection with reviewer data
def update_reviewers_collection(reviewer_id, reviewer_name):
    # Update or insert reviewer data into the collection
    reviewers_collection.update_one(
        {'reviewer_id': reviewer_id},
        {
            '$set': {'reviewer_name': reviewer_name},
            '$inc': {'review_count': 1}
        },
        upsert=True
    )

# Function to get the review count for a reviewer ID or name
def get_review_count(reviewer_id=None, reviewer_name=None):
    # Construct query based on provided parameters
    query = {}
    if reviewer_id:
        query['reviewer_id'] = reviewer_id
    if reviewer_name:
        query['reviewer_name'] = reviewer_name

    # Retrieve reviewer data from the collection
    reviewer = reviewers_collection.find_one(query)
    return reviewer['review_count'] if reviewer else 0

# Example usage of the get_review_count function
review_count_by_id = get_review_count(reviewer_id="123456")
print(f"Number of reviews for reviewer ID '123456': {review_count_by_id}")

review_count_by_name = get_review_count(reviewer_name="John Doe")
print(f"Number of reviews for reviewer name 'John Doe': {review_count_by_name}")

# Update the reviewers collection based on existing data in listingsAndReviews_new
pipeline = [
    {'$unwind': '$reviews'},
    {'$project': {'reviewer_id': '$reviews.reviewer_id', 'reviewer_name': '$reviews.reviewer_name'}},
]

reviews = list(db.listingsAndReviews_new.aggregate(pipeline))

for review in reviews:
    update_reviewers_collection(review['reviewer_id'], review['reviewer_name'])

# Retrieve the top 20 reviewers
top_reviewers = find_top_reviewers()
print("Top 20 Reviewers:")
for reviewer_id in top_reviewers:
    reviewer_name = get_reviewer_name(reviewer_id)
    review_count = get_review_count(reviewer_id=reviewer_id)
    print(f"{reviewer_name} (ID: {reviewer_id}): {review_count} reviews")

Number of reviews for reviewer ID '123456': 0
Number of reviews for reviewer name 'John Doe': 0



KeyboardInterrupt



### Question 10
In order to solve this question, we'll need to go through 2 phases. For ease of reading purposes, we'll solve this question in 3 separate cells.
Since we dispose of different review scores for different metrics, we believe it's best to merge them into an embedded field. As such, on the first cell we will create a function to help us achieve this more efficiently.
On the second cell, we will dedicate ourselves to create a function that will calculate the average for the review score

Let's start by merging the review score fields.s.

In [52]:
#UpdateOne is a class provided by the PyMongo library which allows us to perform an update operation to a single document in a collection, more efficiently.
from pymongo import UpdateOne

#For ease of solving, let's start by creating a function to merge the fields related with review scores.
def merge_review_scores():
    # Define the update operations to merge review scores fields
    update_operations = [
        UpdateOne(
            {},
            [
                {"$set": {"review_scores": {"$mergeObjects": [
                    {"checkin": "$review_scores_checkin"},
                    {"cleanliness": "$review_scores_cleanliness"},
                    {"communication": "$review_scores_communication"},
                    {"location": "$review_scores_location"},
                    {"value": "$review_scores_value"}
                ]}}},
                {"$unset": [
                    "review_scores_checkin", "review_scores_cleanliness",
                    "review_scores_communication", "review_scores_location",
                    "review_scores_rating", "review_scores_value"
                ]}
            ]
        )
    ]

    # Execute the bulk update operation
    db.listingsAndReviews_new.bulk_write(update_operations)

Now, we'll create a function to compute the average review scores.

In [53]:
#Now, we'll create a function to calculate for the inserted property the average review score.
def calculate_average_review_score(property_id):    
# Define the aggregation pipeline to compute the average review score
    pipeline = [
        {"$match": {"_id": property_id}},
        {"$project": {"review_scores_array": {"$objectToArray": "$review_scores"}}},
        {"$unwind": "$review_scores_array"},
        {"$group": {
            "_id": "$_id",
            "avg_review_score": {"$avg": "$review_scores_array.v"}
        }},
        {"$project": {"_id": 0, "avg_review_score": {"$round": ["$avg_review_score", 2]}}}
    ]

    # Execute the aggregation pipeline
    result = list(db.listingsAndReviews_new.aggregate(pipeline))
    return result

In [54]:
# Let's merge the review scores metrics into one embedded field
merge_review_scores()

#Let's test 
example_property_id = '10006546'
average_review_score_result = calculate_average_review_score(example_property_id)

# Print the result
print(average_review_score_result)

[]


### Question 11

In [55]:
#We'll start by creating a function which will, as requested calculate average value for the given period.
def given_time_average_transaction_value(property_id, start_date, end_date):
    
    pipeline = [
        # Match documents based on property ID and transaction date within the given time period
        {"$match": {
            "property_id": property_id,
            "transaction_date": {"$gte": start_date, "$lte": end_date}
        }},
        # Getting the property ID and calculate the average transaction value for it
        {"$group": {
            "_id": "$property_id",
            "avg_transaction_value": {"$avg": "$transaction_value"}
        }}
    ]

    # Execute the aggregation pipeline
    result = list(db.transactions.aggregate(pipeline))

    # defining the outcome, depending on the result.
    if len(result)!=0:
        # getting the average transaction value from the given period.
        avg_transaction_value = result[0]["avg_transaction_value"]
        print(f"The average transaction value for the property with id {property_id}, between {start_date} and {end_date} is ${avg_transaction_value:.2f}")
    else:
        print("No transactions found for the specified property and time period.")

In [56]:
# Testing if our function is working. 
from datetime import datetime

# Specify the property of interest
property_id = '10006546'
# Specify the period of time of interest
start_date = datetime(2000, 1, 1)
end_date = datetime(2010, 12, 31)

# Call the function to calculate the average transaction value
given_time_average_transaction_value(property_id, start_date, end_date)

No transactions found for the specified property and time period.


### Question 12

The first thing we must do is define how to identify the top 10 cities. Since this problem refers to AirBnB listings and Reviews, we can assume that the most popular cities will have a greater number of listed properties. As such we will have to identify the top 10 cities with most repeated `address.market`.

In [57]:
top10 = list(db.listingsAndReviews_new.aggregate([
    # Group by city and count the documents
    {'$group': {'_id': '$address.market', 'count': {'$sum': 1}}},
    # Define counting in descending order
    {'$sort': {'count': -1}},
    # Limiting to top 10
    {'$limit': 10},
    
    # Project both city name and total document count
    {'$project': {'City': '$_id', 'Count': '$count', '_id': 0}}
]))
pprint(top10)

[{'City': 'Istanbul', 'Count': 660},
 {'City': 'Montreal', 'Count': 648},
 {'City': 'Barcelona', 'Count': 632},
 {'City': 'Hong Kong', 'Count': 619},
 {'City': 'Sydney', 'Count': 609},
 {'City': 'New York', 'Count': 607},
 {'City': 'Rio De Janeiro', 'Count': 603},
 {'City': 'Porto', 'Count': 554},
 {'City': 'Oahu', 'Count': 253},
 {'City': 'Maui', 'Count': 153}]


Next, in order to identify each property type (and the respective number of those properties) for each top 10 city we must define a pipeline which aggregates the number of properties for each property type in intended cities. First it should group all data by city and type of property, and then by city to create an array with property types and their counts. It must also calculate the total count of properties for each city,  and sort the cities by the total number of properties in descending order (as it was done on the previous exercise), so that the output retrieves only the results related to the top 10 cities.

In [58]:
pipeline_property_type = [
    {"$group": {
        "_id": {"city": "$address.market", "property_type": "$property_type"},
        "count": {"$sum": 1}
    }},
    {"$group": {
        "_id": "$_id.city",
        "property_types": {
            "$push": {
                "type": "$_id.property_type",
                "count": "$count"
            }
        },
        "total_properties": {"$sum": "$count"}
    }},
    {"$sort": {"total_properties": -1}},
    {"$limit": 10}
]

top10_property_type = list(db.listingsAndReviews_new.aggregate(pipeline_property_type))

pprint(top10_property_type)

[{'_id': 'Istanbul',
  'property_types': [{'count': 10, 'type': 'Townhouse'},
                     {'count': 6, 'type': 'Villa'},
                     {'count': 1, 'type': 'Guest suite'},
                     {'count': 37, 'type': 'House'},
                     {'count': 13, 'type': 'Hotel'},
                     {'count': 6, 'type': 'Hostel'},
                     {'count': 1, 'type': 'Guesthouse'},
                     {'count': 15, 'type': 'Aparthotel'},
                     {'count': 30, 'type': 'Boutique hotel'},
                     {'count': 1, 'type': 'Nature lodge'},
                     {'count': 67, 'type': 'Serviced apartment'},
                     {'count': 413, 'type': 'Apartment'},
                     {'count': 1, 'type': 'Chalet'},
                     {'count': 16, 'type': 'Loft'},
                     {'count': 7, 'type': 'Condominium'},
                     {'count': 5, 'type': 'Other'},
                     {'count': 5, 'type': 'Casa particular (Cuba)'},
         

Next, we will calculate the average price of properties by city (within the top 10 cities).

In [59]:
# Pipeline to calculate the average price in the city
pipeline_average_price = [
    # Group the listings by city and calculate total properties and average price for each city
    {"$group": {
        "_id": "$address.market",
        "total_properties": {"$sum": 1},
        "average_price": {"$avg": "$price"}
    }},
    # Sort the cities by total number of properties in descending order
    {"$sort": {"total_properties": -1}},
    # Limit the result to the top 10 cities
    {"$limit": 10},
    # Project the city name and average price fields
    {"$project": {
        "_id": 0,
        "City": "$_id",
        "Average Price": "$average_price",
    }}
]

result_average_price = list(db.listingsAndReviews_new.aggregate(pipeline_average_price))

pprint(result_average_price)

[{'Average Price': Decimal128('367.9454545454545454545454545454545'),
  'City': 'Istanbul'},
 {'Average Price': Decimal128('100.2330246913580246913580246913580'),
  'City': 'Montreal'},
 {'Average Price': Decimal128('100.9477848101265822784810126582278'),
  'City': 'Barcelona'},
 {'Average Price': Decimal128('762.4781906300484652665589660743134'),
  'City': 'Hong Kong'},
 {'Average Price': Decimal128('197.7142857142857142857142857142857'),
  'City': 'Sydney'},
 {'Average Price': Decimal128('139.6260296540362438220757825370675'),
  'City': 'New York'},
 {'Average Price': Decimal128('525.8059701492537313432835820895522'),
  'City': 'Rio De Janeiro'},
 {'Average Price': Decimal128('69.12815884476534296028880866425993'),
  'City': 'Porto'},
 {'Average Price': Decimal128('212.2964426877470355731225296442688'),
  'City': 'Oahu'},
 {'Average Price': Decimal128('286.5882352941176470588235294117647'),
  'City': 'Maui'}]


In order to extract even for information we decided to calculate the average prices for each property on those same top 10 cities identified previously.

In [60]:
pipeline_average_price_per_type = [
    # Grouping by city and property type, calculating count and average price for each group
    {'$group': {'_id': {'city': "$address.market", 'property_type': "$property_type"},
                'count': {'$sum': 1}, 'average_price': {'$avg': "$price"}}},
    # Grouping again by city, creating an array with property types, counts, and average prices
    {'$group': {'_id': "$_id.city", 'city_total_properties': {'$sum': "$count"},
                'properties': {'$push': {'type': "$_id.property_type",
                                          'count': "$count",
                                          'average_price': "$average_price"}}}},
    # Sorting the cities by the total number of properties in descending order
    {'$sort': {'city_total_properties': -1}},  # Sorting by total number of properties in descending order
    # Limiting the result to the top 10 cities
    {'$limit': 10},
    # Projecting the city name, total properties, city average price, and properties fields
    {'$project': {'_id': 0, 'City': "$_id", 'Total Properties': "$city_total_properties",
                  'Properties': "$properties"}}
]

# Executing the aggregation pipeline
result_average_price_per_type = list(db.listingsAndReviews_new.aggregate(pipeline_average_price_per_type))

# Printing the result
pprint(result_average_price_per_type)

[{'City': 'Istanbul',
  'Properties': [{'average_price': Decimal128('257.80'),
                  'count': 10,
                  'type': 'Townhouse'},
                 {'average_price': Decimal128('1383.166666666666666666666666666667'),
                  'count': 6,
                  'type': 'Villa'},
                 {'average_price': Decimal128('121.00'),
                  'count': 1,
                  'type': 'Guest suite'},
                 {'average_price': Decimal128('276.2972972972972972972972972972973'),
                  'count': 37,
                  'type': 'House'},
                 {'average_price': Decimal128('956.00'),
                  'count': 13,
                  'type': 'Hotel'},
                 {'average_price': Decimal128('122.8333333333333333333333333333333'),
                  'count': 6,
                  'type': 'Hostel'},
                 {'average_price': Decimal128('295.00'),
                  'count': 1,
                  'type': 'Guesthouse'},
           

In [61]:
# Pipeline to aggregate information about the top 3 properties in each city
pipeline_top_properties = [
    # Group the listings by city and include basic information about each property
    {"$group": {
        "_id": "$address.market",
        "properties": {
            "$push": {
                "name": "$name",
                "price": "$price",
                "number_of_reviews": "$number_of_reviews",
                # Add more fields as needed
            }
        }
    }},
    # Sort the properties within each city by certain criteria (e.g., price or number of reviews)
    {"$project": {
        "_id": 0,
        "City": "$_id",
        "top_properties": {
            "$slice": ["$properties", 3]  # Limit to the top 3 properties in each city
        }
    }}
]

# Execute the aggregation pipeline
result_top_properties = list(db.listingsAndReviews_new.aggregate(pipeline_top_properties))

# Print the result
pprint(result_top_properties)

[{'City': 'Istanbul',
  'top_properties': [{'name': 'Charming Flat in Downtown Moda',
                      'number_of_reviews': 1,
                      'price': Decimal128('527.00')},
                     {'name': 'Cozy house at Beyoğlu',
                      'number_of_reviews': 27,
                      'price': Decimal128('58.00')},
                     {'name': 'GOLF ROYAL RESİDENCE TAXİM(1+1):3',
                      'number_of_reviews': 3,
                      'price': Decimal128('838.00')}]},
 {'City': 'Oahu',
  'top_properties': [{'name': 'Ocean View Waikiki Marina w/prkg',
                      'number_of_reviews': 96,
                      'price': Decimal128('115.00')},
                     {'name': 'Makaha Valley Paradise with OceanView',
                      'number_of_reviews': 32,
                      'price': Decimal128('95.00')},
                     {'name': 'Private OceanFront - Bathtub Beach. Spacious '
                              'House',
                 

In [62]:
# Pipeline to find the top 10 cities and their top 3 properties based on average rating
pipeline_top_properties = [
    # Group by city to find the top 10 cities
    {"$group": {
        "_id": "$address.market",
        "count": {"$sum": 1}
    }},
    # Sort by count to get the top 10 cities
    {"$sort": {"count": -1}},
    {"$limit": 10},
    # Lookup to get all properties in each city
    {"$lookup": {
        "from": "listingsAndReviews_new",
        "localField": "_id",
        "foreignField": "address.market",
        "as": "properties"
    }},
    # Unwind to separate each property
    {"$unwind": "$properties"},
    # Unwind again to separate each review
    {"$unwind": "$properties.reviews"},
    # Group by property to calculate average rating
    {"$group": {
        "_id": "$properties._id",
        "avg_rating": {"$avg": "$properties.review_scores_rating"}
    }},
    # Sort properties by highest average rating
    {"$sort": {"avg_rating": -1}},
    # Group by property to keep only the highest average rating
    {"$group": {
        "_id": "$_id",
        "avg_rating": {"$first": "$avg_rating"}
    }},
    # Lookup to get property info
    {"$lookup": {
        "from": "listingsAndReviews_new",
        "localField": "_id",
        "foreignField": "_id",
        "as": "property_info"
    }},
    # Project to select useful fields
    {"$project": {
        "city": {"$arrayElemAt": ["$property_info.address.market", 0]},
        "property_id": "$_id",
        "avg_rating": 1,
        "number_of_reviews": "$property_info.number_of_reviews",
        "price": "$property_info.price",
        "host_is_superhost": "$property_info.host_is_superhost",
        "property_type": "$property_info.property_type",
        "property_name": "$property_info.name"
    }},
    # Group by city to get top 3 properties
    {"$group": {
        "_id": "$city",
        "properties": {
            "$push": {
                "Property ID": "$property_id",
                "Name": "$property_name",
                "Rating": "$avg_rating",
                "Number of reviews": "$number_of_reviews",
                "Superhost": "$host_is_superhost",
                "Type of property": "$property_type",
                "Price": "$price"
            }
        }
    }},
    # Project to rename fields and select top 3 properties
    {"$project": {
        "_id": 0,
        "City": "$_id",
        "Properties": {"$slice": ["$properties", 3]}
    }}
]

# Execute the aggregation pipeline
top10_cities = list(db.listingsAndReviews_new.aggregate(pipeline_top_properties))

# Print the result
pprint(top10_cities)

[{'City': 'Sydney',
  'Properties': [{'Name': ['Ultra Modern Pool House Maroubra'],
                  'Number of reviews': [5],
                  'Price': [Decimal128('328.00')],
                  'Property ID': '19768051',
                  'Rating': 100.0,
                  'Superhost': [False],
                  'Type of property': ['House']},
                 {'Name': ['Close to Coogee beach and fun stuff'],
                  'Number of reviews': [4],
                  'Price': [Decimal128('119.00')],
                  'Property ID': '16167487',
                  'Rating': 95.0,
                  'Superhost': [False],
                  'Type of property': ['Apartment']},
                 {'Name': ['Room on the waterfront'],
                  'Number of reviews': [52],
                  'Price': [Decimal128('85.00')],
                  'Property ID': '12370710',
                  'Rating': 98.0,
                  'Superhost': [True],
                  'Type of property': ['Condomini

Below is a script designed to identify the top 10 cities with the most listed properties. For each of these cities, it determines the top 3 properties based on their average rating. The script then compiles this information into a list, including details such as property ID, name, rating, number of reviews, superhost status, property type, and price. This information can be valuable for users seeking examples of available properties in these popular destinations.

In [63]:
# Define a function to calculate the average rating for a property
def calculate_average_rating(reviews):
    total_rating = 0
    total_reviews = 0
    for review in reviews:
        if 'review_scores_rating' in review:
            total_rating += review['review_scores_rating']
            total_reviews += 1
    if total_reviews == 0:
        return 0
    return total_rating / total_reviews

# Find the top 10 cities
top10_cities = db.listingsAndReviews_new.aggregate([
    {"$group": {"_id": "$address.market", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}},
    {"$limit": 10}
])

# Create a list to store the results
result = []

# Iterate over the top 10 cities
for city in top10_cities:
    city_name = city['_id']
    # Find all properties in the city
    properties = db.listingsAndReviews_new.find({"address.market": city_name})
    # Create a list to store property information
    city_properties = []
    # Iterate over properties to find top 3 based on average rating
    for property in properties:
        property_id = property['_id']
        property_name = property['name']
        number_of_reviews = property['number_of_reviews']
        price = property['price']
        host_is_superhost = property['host_is_superhost']
        property_type = property['property_type']
        # Calculate average rating for the property
        average_rating = calculate_average_rating(property['reviews'])
        # Add property information to the list
        city_properties.append({
            "Property ID": property_id,
            "Name": property_name,
            "Rating": average_rating,
            "Number of reviews": number_of_reviews,
            "Superhost": host_is_superhost,
            "Type of property": property_type,
            "Price": price
        })
    # Sort properties by rating in descending order
    city_properties.sort(key=lambda x: x["Rating"], reverse=True)
    # Take top 3 properties
    top3_properties = city_properties[:3]
    # Add city and top 3 properties to the result list
    result.append({"City": city_name, "Properties": top3_properties})

# Print the result
pprint(result)

[{'City': 'Istanbul',
  'Properties': [{'Name': 'Charming Flat in Downtown Moda',
                  'Number of reviews': 1,
                  'Price': Decimal128('527.00'),
                  'Property ID': '10047964',
                  'Rating': 0,
                  'Superhost': False,
                  'Type of property': 'House'},
                 {'Name': 'Cozy house at Beyoğlu',
                  'Number of reviews': 27,
                  'Price': Decimal128('58.00'),
                  'Property ID': '10092679',
                  'Rating': 0,
                  'Superhost': True,
                  'Type of property': 'Apartment'},
                 {'Name': 'GOLF ROYAL RESİDENCE TAXİM(1+1):3',
                  'Number of reviews': 3,
                  'Price': Decimal128('838.00'),
                  'Property ID': '10115921',
                  'Rating': 0,
                  'Superhost': False,
                  'Type of property': 'Serviced apartment'}]},
 {'City': 'Montreal',
  'Pr

### Question 13

Firstly, we're using a function to randomly select amenities from a list, ensuring that the count doesn't exceed 10. Then, we employ another function to generate a unique host ID for the property's host. This function queries the database to find the highest existing host ID, increments it, and converts it into a string for the new host.

Moving on, we randomly select a city for the property's location from a list of our top 10 cities. Lastly, we combine the selected amenities, the new host ID, and the chosen city to create a new property listing document. This document is then inserted into our database collectiorty.

In [65]:
import random

# Function to randomly select a subset of amenities from a given list
def select_random_amenities(amenities_list, max_count):
    num_amenities = random.randint(1, min(max_count, len(amenities_list)))
    return random.sample(amenities_list, num_amenities)

# Generate a unique host ID for the new property
def generate_new_host_id(collection):
    max_host_id = collection.find().sort("host_id", -1).limit(1)[0]['host_id']
    new_host_id = str(int(max_host_id) + 1)
    return new_host_id

# Choose a random city from a list of top cities
def choose_random_city(top_cities):
    return random.choice(top_cities)

# Select amenities for the new property
selected_amenities = select_random_amenities(suggested_typical_amenities, 10)

# Generate a new host ID
new_host_id = generate_new_host_id(db.listingsAndReviews_new)

# Choose a city from the top 10 cities
city = choose_random_city(top10)

# Add a new property to the collection
new_property = {
    "amenities": selected_amenities,
    "host_id": new_host_id,
    "address": {"market": city}
}
db.listingsAndReviews_new.insert_one(new_property)

InsertOneResult(ObjectId('66238db838d7dcb2cca28548'), acknowledged=True)

Now we check the new collection we created.

In [66]:
result=list(db.listingsAndReviews_new.aggregate([{"$match": {"host_id": new_host_id}}]))

pprint(result)

[{'_id': ObjectId('66238db838d7dcb2cca28548'),
  'address': {'market': {'City': 'Rio De Janeiro', 'Count': 603}},
  'amenities': ['Essentials', 'Wifi'],
  'host_id': '99997585'}]


### Question 14

# ESTE CÓDIGO É PARA APAGAR DEPOIS

In [67]:
# 1. Showing the top 20 reviewers and the count of the number of reviews of each of these reviewers
top20_reviewers = list(db.Reviews.aggregate([
    # Group by reviewer (id and name) and count the number of reviews for each reviewer
    {"$group": {"_id": {"id": "$reviewer_id", "name": "$reviewer_name"}, "Count": {"$sum": 1}}},
    # Sort by number of reviews in descending order
    {"$sort": {"Count": -1}},
    # Using the $project operator to specify the fields 'reviewer_id' and 'reviewer_name' and the number of reviews (Count)
    {"$project": {"_id": "$_id.id", "Reviewer Name": "$_id.name", "Count": 1}},
    # Limit the result to the top 20 reviewers
    {"$limit": 20}
]))

print("Top 20 reviewers:")
for i in top20_reviewers:
            print('Name: ' + str(i['Reviewer Name']) + ', ID: ' + str(i['_id'])+', Reviews: ' + str(i['Count']))

Top 20 reviewers:
Name: Filipe, ID: 20775242, Reviews: 24
Name: Nick, ID: 67084875, Reviews: 13
Name: Uge, ID: 2961855, Reviews: 10
Name: Thien, ID: 162027327, Reviews: 9
Name: Lisa, ID: 20991911, Reviews: 9
Name: Jodi, ID: 12679057, Reviews: 8
Name: Todd, ID: 60816198, Reviews: 8
Name: Lisa, ID: 69140895, Reviews: 8
Name: Courtney, ID: 55241576, Reviews: 8
Name: David, ID: 1705870, Reviews: 8
Name: David, ID: 78093968, Reviews: 7
Name: Lance, ID: 47303133, Reviews: 7
Name: Gonzalo, ID: 73708321, Reviews: 6
Name: Megan, ID: 25715809, Reviews: 6
Name: Branden, ID: 128210181, Reviews: 6
Name: Dan, ID: 34005800, Reviews: 6
Name: Karen, ID: 24667379, Reviews: 6
Name: Chris, ID: 86665925, Reviews: 6
Name: Erik, ID: 61469899, Reviews: 6
Name: Pierre, ID: 93859831, Reviews: 6


----------------------------------------------------------------------------

In [68]:
top20_reviewers

[{'Count': 24, '_id': '20775242', 'Reviewer Name': 'Filipe'},
 {'Count': 13, '_id': '67084875', 'Reviewer Name': 'Nick'},
 {'Count': 10, '_id': '2961855', 'Reviewer Name': 'Uge'},
 {'Count': 9, '_id': '162027327', 'Reviewer Name': 'Thien'},
 {'Count': 9, '_id': '20991911', 'Reviewer Name': 'Lisa'},
 {'Count': 8, '_id': '12679057', 'Reviewer Name': 'Jodi'},
 {'Count': 8, '_id': '60816198', 'Reviewer Name': 'Todd'},
 {'Count': 8, '_id': '69140895', 'Reviewer Name': 'Lisa'},
 {'Count': 8, '_id': '55241576', 'Reviewer Name': 'Courtney'},
 {'Count': 8, '_id': '1705870', 'Reviewer Name': 'David'},
 {'Count': 7, '_id': '78093968', 'Reviewer Name': 'David'},
 {'Count': 7, '_id': '47303133', 'Reviewer Name': 'Lance'},
 {'Count': 6, '_id': '73708321', 'Reviewer Name': 'Gonzalo'},
 {'Count': 6, '_id': '25715809', 'Reviewer Name': 'Megan'},
 {'Count': 6, '_id': '128210181', 'Reviewer Name': 'Branden'},
 {'Count': 6, '_id': '34005800', 'Reviewer Name': 'Dan'},
 {'Count': 6, '_id': '24667379', 'Revi

In [69]:
# Check the fields of reviews so that we can write one properly
db.Reviews.find_one()

{'_id': '58663741',
 'listing_id': '10006546',
 'date': datetime.datetime(2016, 1, 3, 5, 0),
 'reviewer_id': '51483096',
 'reviewer_name': 'Cátia',
 'comment': 'A casa da Ana e do Gonçalo foram o local escolhido para a passagem de ano com um grupo de amigos. Fomos super bem recebidos com uma grande simpatia e predisposição a ajudar com qualquer coisa que fosse necessário.\r\nA casa era ainda melhor do que parecia nas fotos, totalmente equipada, com mantas, aquecedor e tudo o que pudessemos precisar.\r\nA localização não podia ser melhor! Não há melhor do que acordar de manhã e ao virar da esquina estar a ribeira do Porto.'}

In [ ]:
property_id = list(db.listingsAndReviews_new.aggregate([
    {"$match": {"host_id": new_host_id}},
    {"$project": {"_id": 1}}
]))[0]["_id"]
property_id

Now that the we know what are fields of the review, we can proceed to writing one.

In [73]:
from datetime import datetime

new_review = {
    "listing_id": property_id,
    "reviewer_id": "20775242",
    'reviewer_name': 'Filipe',
    "comments": "I loved this house so much! Such great memories! Best birthday party ever! I even heard my friends talking about maybe buying it to me...",
    "date": datetime(2024, 5, 7) # One of our team member's is also called Filipe, we chose this date as his birthday in his honor
}
# Add a new review to the property
db.Reviews.insert_one(new_review)

InsertOneResult(ObjectId('66238f3438d7dcb2cca28549'), acknowledged=True)

In [78]:
review = db.Reviews.find_one({"listing_id": property_id})
pprint(review)

{'_id': ObjectId('66238f3438d7dcb2cca28549'),
 'comments': 'I loved this house so much! Such great memories! Best birthday '
             'party ever! I even heard my friends talking about maybe buying '
             'it to me...',
 'date': datetime.datetime(2024, 5, 7, 0, 0),
 'listing_id': {'_id': ObjectId('66238db838d7dcb2cca28548'),
                'address': {'market': {'City': 'Rio De Janeiro', 'Count': 603}},
                'amenities': ['Essentials', 'Wifi'],
                'host_id': '99997585'},
 'reviewer_id': '20775242',
 'reviewer_name': 'Filipe'}


### Question 15

We'll first augment our property documents by introducing a new review metric named "x_factor" with a fixed score of 10 for the most recent listing. Following this update, we'll execute an aggregation pipeline that we previously developed to compute the average review score across all metrics for this specific property. This pipeline involves projecting the review scores into an array format, unwinding the array for individual metric analysis, aggregating the scores, and finally rounding off the average score to ensure clarity. By executing this pipeline, we'll accurately determine the overall performance of the property, incorporating the newly added "x_factor" metric into our analysis.

In [80]:
# Adding the new review metric to the new document
db.listingsAndReviews_new.update_one(
    {"_id": new_property}, 
    {"$set": {"review_scores.x_factor": 10}}
)

# Calculating the average review score using an aggregation pipeline
pipeline_score = [
    {"$match": {"_id": property_id}},
    {"$project": {
        "review_scores_array": {"$objectToArray": "$review_scores"}
    }},
    {"$unwind": "$review_scores_array"},
    {"$group": {
        "_id": "$_id", 
        "avg_review_score": {"$avg": "$review_scores_array.v"}
    }},
    {"$project": {
        "_id": 0, 
        "avg_review_score": {"$round": ["$avg_review_score", 2]}
    }}
]

# Executing the aggregation pipeline
result_score = list(db.listingsAndReviews_new.aggregate(pipeline_score))

# Print the result
pprint(result_score)

[]
